# All units in milliseconds unless otherwise specified

information_processing_rate:
    low: 0.5  # Minimum information processing rate
    high: 1.111  # Maximum information processing rate

self_paced:
    max_wrong_count: 5  # Number of wrong answers before the test ends
    max_right_count: 4  # Number of right answers before self-paced test ends

machine_paced:
    max_wrong_count: 5  # Number of wrong answers before the duration is increased
    max_right_count: 1  # Number of right answers before the duration is decreased 
    max_count: 8  # TODO
    max_start_duration: 2100  # Initital duration
    not_there: 0  # TODO
    not_there_disabled: true  # TODO

    blocking:
        no_input_count: 2  # How many test screens with no response to declare a "block"
        max_block_display_time_duration: 135  # After blocking, wait for response, then resume with `machine_pace` + this amount
    slowdown:
        initial_display_time_duration: 75  # Ms slower than `self_paced_average` to start machine_paced
        block_display_time_duration: 300  # When there are no responses to two test screens, slow by this amount
        wrong_display_time_duration: 100  # When there is are `max_wrong_count` wrong answers, slow by this amount

    speedup:
        speedup_display_time_duration: 33  # When there are `max_right_count` right answers, speed up by this amount
        speedup_on_correct: true  # Whether to speed up on correct answers
        speedup_on_wrong: false  # Whether to speed up on wrong answers
        speedup_on_noinput: false  # Whether to speed up on no input
        speedup_base: -25  # TODO
        speedup_mod: 0  # TODO

no_response_timeout: 10_000  # Time in milliseconds before the test ends if no response is given
max_test_duration_timeout: 120_000  # Maximum time in milliseconds before the test ends

n_endmode_rounds: 2  # Number of extra rounds at the end of the test

mp_rollmean_size: 8  # TODO
mp_rollmean_min: 0.6  # TODO
mp_input_ends_round: true  # TODO
mp_rt_buffer_size: 3  # TODO

bpRoundCount: 3  # TODO
n_inversecolordisplay: 3  # TODO
p_displayother: 0.25  # TODO
p_invert_letnum: 0.25  # TODO


anti_spoofing:
    max_bad_tests_in_session: 3  # Number of bad tests because retest is no longer an option

tutorial:  # TODO
    tutorial_nSPRounds: 12
    tutorial_nMPRounds: 8
    tutorial_mpRoundStartDuration: 2100
    tutorial_mpRoundDurationDelta: -200

    number_of_training_rounds: 2  # Number of training rounds

general:
    # Whether to save round data and have the ability for the user to download it - 
    save_round_data: true  # Or to automatically send it to another user

